### ISSUE TITLE
Difficult to tell whether shuffle is toggled on or off

### ISSUE THREAD

**Issue by benknight** [chrisxclash/play-midnight#10]
So this is shuffle OFF:
![screen shot 2015-04-16 at 11 13 38 am](https://cloud.githubusercontent.com/assets/786691/7188034/c57af7ce-e429-11e4-9f86-96dda02add43.png)

This is shuffle ON:
![screen shot 2015-04-16 at 11 13 30 am](https://cloud.githubusercontent.com/assets/786691/7188037/cac8ce90-e429-11e4-9402-772e37e8ecba.png)

(I think.. I might have gotten those backwards, which illustrates the point)

**Comment by chrisxclash** [comment]
Which accent color are you using? And is this a retina or non-retina display?

**Comment by benknight** [comment]
This was the grayscale theme, which is the only theme where it's really an issue since there's no highlight color.  This was a retina display but I think that's irrelevant here.

**Comment by chrisxclash** [comment]
Ah yeah, I see what you mean. I think that whole color scheme needs a rework, honestly. I threw it together pretty fast without testing, but it looks like the active color is too close to the disabled states in general.

I've found a neat way to (hopefully) make adding new colors/custom colors much easier that should remove the need for changing Google's sprites, but I've been short on time with a new job right now. I'm hoping that will become part of v2.0 rework.

Might take me a bit to get to this grayscale issue, so apologies, but you're welcome to take a stab at redoing it and shoot a pull request if you want! :+1:
