### ISSUE TITLE
We can remove the code for pull request #6

### ISSUE THREAD

**Issue by benknight** [chrisxclash/play-midnight#11]
Google has pushed some design updates since we merged #6 which make the cards responsive to screen size, so we should get rid of this code since it's not doing anything useful anymore and could potentially cause visual bugs.

**Comment by benknight** [comment]
Whoops, my bad, you already got rid of it [here](https://github.com/chrisxclash/play-midnight/commit/8aa0f04735759795c93c34af7ab5ffa613e32d87#diff-be0a9b03360cd2cfc66fe86c6cbbae7bL1180).  Good man!

**Comment by chrisxclash** [comment]
Haha yeah, someone on Reddit complained about how stretched out they were and I realized it was because of how they %'s were applied.

All is well!
