### ISSUE TITLE
Google Play Music UI update breaks play-midnight

### ISSUE THREAD

**Issue by douglas-mason** [chrisxclash/play-midnight#12]
Unfortunately, it looks like a recent update to the Play Music UI has affected Play Midnight.
Here's screenshots of before and after enabling the extension.

![screenshot 2015-05-14 14 13 24](https://cloud.githubusercontent.com/assets/1195453/7638554/b4c61b54-fa43-11e4-9f72-682f2771caa3.png)

![screenshot 2015-05-14 14 12 04](https://cloud.githubusercontent.com/assets/1195453/7638552/b1aee4d2-fa43-11e4-97f0-68dde574e81c.png)

**Comment by rlemon** [comment]
Can also confirm. my menu is now hidden by an overlay which I cannot seem to dismiss without removing the element from the inspector..

**Comment by chrisxclash** [comment]
Yup, I'll be taking a look at restyling everything this weekend and hopefully getting something pushed out for next week.

As of right now, it's probably best to just disable it until I can get something going.

**Comment by douglas-mason** [comment]
thanks @chrisxclash , great work on this plugin, I love it

**Comment by chrisxclash** [comment]
In case you guys didn't see on reddit/chrome/etc I've pushed the newest update to the Chrome webstore. It's currently blue accent only while I'm fixing up the options page, but should have that out this week.

Webstore: https://chrome.google.com/webstore/detail/play-midnight-for-google/ljmjmhjkcgfmfdhgplikncgndbdeckci

Thanks for the support!
