### ISSUE TITLE
Update Play Midnight to Latest Play Music UI changes

### ISSUE THREAD

**Issue by Arilas** [chrisxclash/play-midnight#14]
After update, I have troubles with "Play queue" that doesn't work properly. Also Google in "Play Queue" added new white gradient, that with "Play Midnight" looks ugly.

The troubles with "Play Queue":
1. Open it
2. Try to click outside to close this menu
3. Click was triggered in wrong place (menu is reopened)

![screenshot from 2015-10-07 16-16-41](https://cloud.githubusercontent.com/assets/3540524/10338454/dc489272-6d0e-11e5-8627-b08b8fba4aca.png)

**Comment by chrisxclash** [comment]
Thanks for the update. I haven't received these changes from Google yet, so it's hard for me to look into them. As soon as I get their changes I'll work on it.

As for the click triggering, etc. I'm not really sure what would be causing that. I don't think anything I'm changing should be causing that, but maybe the extended queue is.

Can you try disabled the "Extended Queue" option and see if the click issue still happens?

Thanks!

**Comment by Arilas** [comment]
As I see, Google rollback this changes(checked by structure of Queue Menu). So everything is works again.

**Comment by bkromhout** [comment]
I'm actually not sure that Google did rollback the changes. While I'd never seen them before, today I opened a playlist and saw this:
<img width="1047" alt="screen shot 2015-10-13 at 3 33 12 pm" src="https://cloud.githubusercontent.com/assets/4447359/10465996/bf758384-71bf-11e5-81b5-c92b32551a3e.png">

**Comment by bkromhout** [comment]
To be clear, I'm only seeing the very obvious gradient issues. Not any of the other issues that Arilas mentioned.

**Comment by chrisxclash** [comment]
They just pushed out a new change. I'll look into it tonight. I actually see the changes this time so it's an easy fix.

**Comment by bkromhout** [comment]
Awesome, thanks for the prompt reply!

**Comment by chrisxclash** [comment]
Yup, no worries! Thanks for letting me know!

**Comment by chrisxclash** [comment]
All fixed up in v2.2.2! Should reach you guys soon.
