### ISSUE TITLE
v2.3.0 is broken with the latest GPM update

### ISSUE THREAD

**Issue by PachowStudios** [chrisxclash/play-midnight#15]
I can't save any options, and the sidebar is missing.

Love the project <3

**Comment by chrisxclash** [comment]
Yup, already aware. Just waiting on the changes to hit me so I can work on it. Thanks for the support!

More details here: https://www.reddit.com/r/PlayMidnight/comments/3pujoy/breakage_new_google_changes_coming_out_things_may/

**Comment by PachowStudios** [comment]
Damn you're fast! I might as well close this then. Thanks!
