### ISSUE TITLE
New elements/pages in a recent update are unthemed.

### ISSUE THREAD

**Issue by bkromhout** [chrisxclash/play-midnight#29]
Hi there, just wanted to let you know that as of the (very recent) update to Google Play Music, there are a couple of unthemed areas (not unexpected, since they appear to be totally new).

If you need any extra detail, don't hesitate to ask!

### Right-hand-side "Playlists" Sidebar

A new sidebar specifically for playlists has been added. You access the sidebar using the new button in the top bar which has (aptly) a playlist icon:
![screen shot 2016-08-19 at 2 47 31 pm](https://cloud.githubusercontent.com/assets/4447359/17820690/07f1b29e-661c-11e6-9796-b3d6ade9bdbb.png)

And then it slides out, and currently looks like this:
![screen shot 2016-08-19 at 2 46 20 pm](https://cloud.githubusercontent.com/assets/4447359/17820693/0f1b7fb4-661c-11e6-897d-620453dcfea7.png)

### "Upgrade to family plan" Page

There is now a new page accessible in the existing (left-hand-side) sidebar when you click button which is above the "Play Midnight" one in this screenshot:
![screen shot 2016-08-19 at 2 53 52 pm](https://cloud.githubusercontent.com/assets/4447359/17820851/c4b9c7d6-661c-11e6-87dc-3576a1f73a92.png)

It takes you to a completely new page, which is scrollable, that has some issues on the light and dark areas:
![screen shot 2016-08-19 at 2 54 46 pm](https://cloud.githubusercontent.com/assets/4447359/17820893/f8e3da42-661c-11e6-9210-6fb8cd7fa0b4.png)
The only thing difficult in the light area is that the text next to the checkmark at the bottom is difficult to read

![screen shot 2016-08-19 at 2 55 04 pm](https://cloud.githubusercontent.com/assets/4447359/17820905/079c1f40-661d-11e6-9484-dcd1428a2429.png)
The dark area is much worse; the header text of "What You'll Get", as well as the table columns' headings ("Features", "Free", and "Unlimited" from left to right) are nearly unreadable.

In addition, while I'm unsure if this is a Google-side or Play Midnight-side issue, the hamburger button which flies out the left-hand sidebar is not present on this screen.

**Comment by chrisxclash** [comment]
Yeah, I just heard word of these things on Reddit as well. Appreciate you creating the issue.

I'll try and tackle some of the bigger issues this weekend.

And just to answer your question about the hamburger, that is indeed from Play Midnight, due to using the static sidebar option.

Thanks again,
Chris

**Comment by bkromhout** [comment]
No problem!

I don't use the static sidebar option, but since it now appears that the left sidebar (well, neither of them really) can actually stay on the screen at all times, I can understand how it might break it. Now they auto-hide when you click off of them.

**Comment by chrisxclash** [comment]
Hey bud, I've worked on getting some things fixed up and removed a few broken options. However, I'm not seeing the "Upgrade to Family Plan" on my end. Might be cause I'm on a trial right now or something.

Could you see if you can shoot me a link to the family plan page and I'll try and get it updated on the next go? Thanks!

**Comment by bkromhout** [comment]
Sure thing, here you go: https://play.google.com/music/listen?u=0#/sulp

**Comment by chrisxclash** [comment]
Welp, sadly I can't actually get to that page. I just get redirected to the main site. If you want to take a stab at it and submit a PR I'd be happy to pull it in for you.

Thanks

**Comment by bkromhout** [comment]
I was just about to see what I could figure out this afternoon, only to find that the page is no longer appearing for me 😒 If it appears again in the future, I'll look at it.

On a totally different note, panel which shows the list of currently playing songs (the "queue" I guess?) is suddenly showing some odd behavior, the currently playing song's row has some unthemed elements as you can see here:

![screen shot 2016-09-09 at 12 06 42 pm](https://cloud.githubusercontent.com/assets/4447359/18394070/23664434-7686-11e6-9e90-c70669c56175.png)

I'll see if I can make heads-or-tails of anything, but I'm no whiz, so I can't promise anything.

**Comment by geudrik** [comment]
Confirming that I'm also seeing now playing row issues, as shown above. 

![screen shot 2016-09-13 at 11 24 04 am](https://cloud.githubusercontent.com/assets/2020115/18479877/a1c6bb76-79a4-11e6-8177-0665d1130733.png)

**Comment by chrisxclash** [comment]
Fixed issues with now playing row styling. Reopen a new issue if the family page happens to show up again. Thanks!
