### ISSUE TITLE
Dark gray text on even darker gray background

### ISSUE THREAD

**Issue by Gnarfoz** [chrisxclash/play-midnight#33]
In some places, like the new "refine suggestions" flow, there's a dark gray font color being used on even darker gray background. It's quite unreadable. ;)

For example:
![image](https://cloud.githubusercontent.com/assets/65654/20306142/2ab33b9c-ab39-11e6-80d4-656541a0ac30.png)
Original:
![image](https://cloud.githubusercontent.com/assets/65654/20306147/2febf432-ab39-11e6-8929-0ca6089ace48.png)
(There's also a non-styled white bar at the bottom, but I just noticed that now.)

Hm, I thought I remembered it happening in more areas, but maybe some of those went away with this week's redesign.

**Comment by chrisxclash** [comment]
Ahh, okay. I hardly ever dig into these types of pages when I use it myself. I usually end up clicking around to find the pages you guys find, but I never seem to be able to, lol.

How does one get to this page?

**Comment by Gnarfoz** [comment]
This one is new this week, it's under Settings > General > Improve your recommendations.

**Comment by chrisxclash** [comment]
Perfect, I see what you're talking about now. I'll try and look into it tonight. Thanks!

**Comment by chrisxclash** [comment]
Should be all fixed up, just pushed out v2.4.1
