### ISSUE TITLE
Zero text/bg contrast in contextual menus

### ISSUE THREAD

**Issue by L-P** [chrisxclash/play-midnight#34]
Dark text on dark background and light text on light background when highlighting.

![black](https://cloud.githubusercontent.com/assets/947312/20341794/fb74debc-abe7-11e6-9bee-14f46a2fb9aa.png)

Version: Play Midnight for Google Play Music™ 2.4.0

**Comment by chrisxclash** [comment]
Ugh, this is becoming so hard to diagnose. You're like the 4th person to report this and yet I can't see the issue on my end. 

I might need someone with html skill to look into this and give me some html markup/class names.

**Comment by L-P** [comment]
The original color `#dcdcdc` comes from a `.body, .body.material`
selector in Play Midnight and gets overriden to `#212121` in the
selector `.material .goog-menu .goog-menuitem .goog-menuitem-content`
from `listenstyles.css`.

The menu hierarchy is as follows: 
```
<div class="goog-menu goog-menu-vertical album-menu">
    <div class="goog-menuheader goog-menuheader-disabled"></div>

    <!-- Repeat block per menu item {{{ -->
    <div class="goog-menuitem">
        <div class="goog-menuitem-content">
            …
        </div>
    </div>
    <!-- }}} -->
</div>
```

The `.goog-menuitem-content` get the wrong style here, their parent and
children seem fine.

**Comment by chrisxclash** [comment]
I seem to have a selector matching that in the Play Midnight styles, but for some reason it's being overridden. I've added an important flag on it for now since I'm not actually able to diagnose it myself. I'm hoping it's a specificity thing that can be fixed lazily for now.

I've heard from someone else who was originally having the issue that it went away, so I'm hoping it's just a slow rollout on Google's end.

**Comment by chrisxclash** [comment]
I've pushed up v2.4.1, hopefully that fixes this (I just guessed), or Google fixes it on their end soon.

**Comment by L-P** [comment]
v2.4.1 fixed it, thanks.

The :hover is still white on white, I'll wait and see if this is because of a slow rollout on Google's end.

**Comment by L-P** [comment]
Same bug on the queue:
![uv](https://cloud.githubusercontent.com/assets/947312/20391707/d39bd3b2-acd4-11e6-9ec0-2ca49e31d1ba.png)

Should I also wait on this one or do you have a repro @chrisxclash ?

**Comment by chrisxclash** [comment]
Holy buns, sorry I didn't see the second part to this issue. Preferably if I can get a PR for the fixes to the menu and queue that'd be helpful for me. I still don't have this issue on my end, so I don't want to just start firing at random and hoping I can fix it. I'm going to put a post on Reddit too to see if someone can submit a PR for this that is also getting the issue.

Thanks!

**Comment by L-P** [comment]
I'll try fixing it this week.

**Comment by chrisxclash** [comment]
I appreciate it!
