### ISSUE TITLE
Confused by the arrows in thumbs up playlist

### ISSUE THREAD

**Issue by meffect** [chrisxclash/play-midnight#38]
My thumbs up playlist, has these weird arrows next to each song. One big up arrow, and two diagonal arrows. No idea what they do but they are a major eye sore

![screenclip](https://cloud.githubusercontent.com/assets/1799758/25034468/947361d8-209b-11e7-805a-79992702e93a.png)

**Comment by chrisxclash** [comment]
These are actually a Bug with the "Large Song Table" option. I'll be trying
to fix it here shortly, but in the meantime you can disable that option
temporarily until I can get a fix out. Sorry about that!

-- 
Chris Tieman

**Comment by meffect** [comment]
Oh ok cool Thanks

**Comment by chrisxclash** [comment]
Just pushed up a fix (I think) for this in v2.4.6. If you have any issues with it when you get the new update, feel free to open another ticket
