### ISSUE TITLE
Page heading backgrounds same colour as font

### ISSUE THREAD

**Issue by brettgoss** [chrisxclash/play-midnight#39]
The headings for the artist pages, playlists and radio stations are no longer being targeted to change the font from black to something lighter. 
<img width="1202" alt="screen shot 2017-04-18 at 4 13 29 pm" src="https://cloud.githubusercontent.com/assets/1578328/25156925/af0edfc6-2452-11e7-9a08-868c7d03d8ec.png">
<img width="692" alt="screen shot 2017-04-18 at 4 25 14 pm" src="https://cloud.githubusercontent.com/assets/1578328/25157047/a333d502-2453-11e7-99d5-ceec403067f0.png">

**Comment by brettgoss** [comment]
Double clicking the `<style scope="gpm-detail-page-header-0">` tag near the bottom of the page to edit it and then hitting return seems to temporarily solve the issue. Not too sure what's going on there. <img width="569" alt="screen shot 2017-04-18 at 4 30 15 pm" src="https://cloud.githubusercontent.com/assets/1578328/25157170/653a7480-2454-11e7-94ae-0e5457293f53.png">
<img width="807" alt="screen shot 2017-04-18 at 4 30 29 pm" src="https://cloud.githubusercontent.com/assets/1578328/25157188/8a2575b0-2454-11e7-845a-e9b82af44fcf.png">

**Comment by chrisxclash** [comment]
They've just updated the markup recently, so I'll have to update the styles to match.

Appreciate you letting me know though!

**Comment by chrisxclash** [comment]
Just pushed up a fix for this in v2.4.6
