### ISSUE TITLE
Cannot open Options after Play Music update

### ISSUE THREAD

**Issue by Arilas** [chrisxclash/play-midnight#40]
Google updated design of sidebar and after this changes, there's no option for open "Play Midnight" Options.

![image](https://user-images.githubusercontent.com/3540524/28529646-c7740fee-7099-11e7-95db-0555e89c03f0.png)

**Comment by chrisxclash** [comment]
Do you by chance use any Adblockers? uBlock seems to be a culprit of making those go away with an update they added recently. I'll have dig in at some point as to why it happens, but if you are using an adblocker, try disabling it and see if the options come back.

Thanks for opening up an issue for me though!

**Comment by bknab** [comment]
Thanks chrisxclash, I was running into this as well.  I do use uBlock and I was able to add `https://play.google.com/music/listen*` to my whitelist which resolved the issue for me.

**Comment by chrisxclash** [comment]
I've updated how the FAB is injected in 2.4.8 and it seems to not be nuked by adblockers anymore that I can see. Closing this for now, but let me know if it comes back for you guys!
