### ISSUE TITLE
(not bug) Play-midnight affect Chromecast style?

### ISSUE THREAD

**Issue by skandl** [chrisxclash/play-midnight#45]
Hi, this is not a bug, more of a feature request and/or discussion. I'm curious if you or other devs have had experience styling the Play Music's chromecast display, or know if that's even feasible?

**Comment by chrisxclash** [comment]
I'm speaking purely out of a guess, but I assume it's probably not possible without doing some crazy finaggling with the Chromecast. I haven't looked into Chromecast dev at all, but I assume Google doesn't give you too much freedom for modifying existing apps, only for creating your own. I could be wrong though, but that's just my best guess.
