### ISSUE TITLE
Style updates from Google have caused some small display issues

### ISSUE THREAD

**Issue by benknight** [chrisxclash/play-midnight#5]
Looks like Google pushed some style updates (which are rather nice actually) that caused a few things to look weird with the extension.  As far as I can tell it's all non-critical, but worth fixing:

![screen shot 2015-01-19 at 11 10 49 am](https://cloud.githubusercontent.com/assets/786691/5806207/f1edf9c0-9fcb-11e4-9265-b0f7fcceb823.png)
![screen shot 2015-01-19 at 11 10 38 am](https://cloud.githubusercontent.com/assets/786691/5806208/f1f05260-9fcb-11e4-9201-40fbea9ca1a0.png)

1. 1px border around "..." button in currently playing bar at the bottom.
1. Current nav item text is play-orange, not in suit with selected midnight theme's palette.
1. "Music" title item in nav sidebar has weird alignment

**Comment by chrisxclash** [comment]
Yeah, I actually threw a quick post about this up on Reddit a few days ago. From looking at the code it seems they're adding some sort of new material stuff (a la Lollipop) so I was holding off for a week or so to see if they made any drastic changes. I'll throw together a fix for it today though, I think. It's been a while and I haven't seen anything else break.

Thanks for the heads up!
